### ISSUE TITLE
Weapon/Case Class

### ISSUE THREAD

**Issue by macksjeremy** [SeanMiller969/SMAB#13]
Should include a rarity system and a damage system. Not all weapons have all damage levels. All cases do not have the same rarity distribution. Case should have a EV calculation.

**Comment by macksjeremy** [comment]
I want to parse into this ASAP

**Comment by macksjeremy** [comment]
By weapon I mean individual skin.

**Comment by johncs00** [comment]
Should be ready to go for use, hit me with any issues.
