### ISSUE TITLE
figure out the math that needs to go on.

### ISSUE THREAD

**Issue by sm1ll3r** [SeanMiller969/SMAB#4]
determine the math that needs to go on in our project.

**Comment by johncs00** [comment]
ok

**Comment by macksjeremy** [comment]
Isn't it just compound probability?

**Comment by sm1ll3r** [comment]
Should be straight forward compound probability with possible analysis of pass data later.

**Comment by sm1ll3r** [comment]
Should be straight forward compound probability with possible analysis of past data later.
